# ▀█▀ █▄ ▄█ █ █ ▀▄▀   ▄▀▀ ▄▀▄ █▄ █ █▀ █ ▄▀ 
#  █  █ ▀ █ ▀▄█ █ █   ▀▄▄ ▀▄▀ █ ▀█ █▀ █ ▀▄█

# ▄▀  ██▀ █▄ █ ██▀ █▀▄ ▄▀▄ █  
# ▀▄█ █▄▄ █ ▀█ █▄▄ █▀▄ █▀█ █▄▄
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -g set-clipboard on
set -g default-terminal "${TERM}"
set -g mouse on

# █▄▀ ██▀ ▀▄▀ ██▄ █ █▄ █ █▀▄ █ █▄ █ ▄▀  ▄▀▀
# █ █ █▄▄  █  █▄█ █ █ ▀█ █▄▀ █ █ ▀█ ▀▄█ ▄██
set -g prefix ^B
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# █▀▄ █   █ █ ▄▀  █ █▄ █ ▄▀▀
# █▀  █▄▄ ▀▄█ ▀▄█ █ █ ▀█ ▄██
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# ▄▀▀ ▄▀▄ █   ▄▀▄ █▀▄ ▄▀▀ ▄▀▀ █▄█ ██▀ █▄ ▄█ ██▀
# ▀▄▄ ▀▄▀ █▄▄ ▀▄▀ █▀▄ ▄██ ▀▄▄ █ █ █▄▄ █ ▀ █ █▄▄
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'
set -g @rose_pine_host 'on'
set -g @rose_pine_date_time ''
set -g @rose_pine_user 'on'
set -g @rose_pine_directory 'on'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'

# ██▄ ▄▀▄ ▄▀▄ ▀█▀ ▄▀▀ ▀█▀ █▀▄ ▄▀▄ █▀▄   █▀▄ █   █ █ ▄▀  █ █▄ █ ▄▀▀
# █▄█ ▀▄▀ ▀▄▀  █  ▄██  █  █▀▄ █▀█ █▀    █▀  █▄▄ ▀▄█ ▀▄█ █ █ ▀█ ▄██
run '/opt/homebrew/opt/tpm/share/tpm/tpm'

